all:
	gcc ../arithmetic/decimal_arithmetic.h \
	../another/decimal_another.h \
	../comparison/decimal_comparison.h \
	../core/constants.h ../core/decimal_core.h \
	../MyLib/style.h \
	../s21_decimal.c \
	../s21_decimal.h \
	# ../arithmetic/div.c \
	../arithmetic/fmod.c \
	../arithmetic/mul.c \
	../arithmetic/sub.c \
	../another/balancing.c 
	../another/bank_round.c \
	../another/s21_floor.c 
	../another/s21_neg.c 
	../another/s21_round.c \
	../another/s21_truncate.c \
	../comparison/s21_eq.c ../comparison/s21_gr_or_eq.c \
	../comparison/s21_gr.c ../comparison/s21_less_or_eq.c \
	../comparison/s21_less.c ../comparison/s21_not_eq.c \
	../core/bit.c ../core/decimal.c ../core/exponent.c \
	../core/shift.c ../core/sign.c \
	../arithmetic/add.c -o test -lgmp