# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/nanadaug/CLionProjects/s21_decimal

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/nanadaug/CLionProjects/s21_decimal

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nanadaug/CLionProjects/s21_decimal/CMakeFiles /Users/nanadaug/CLionProjects/s21_decimal//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nanadaug/CLionProjects/s21_decimal/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named s21_decimal

# Build rule for target.
s21_decimal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 s21_decimal
.PHONY : s21_decimal

# fast build rule for target.
s21_decimal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/build
.PHONY : s21_decimal/fast

src/another/s21_floor.o: src/another/s21_floor.c.o
.PHONY : src/another/s21_floor.o

# target to build an object file
src/another/s21_floor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/src/another/s21_floor.c.o
.PHONY : src/another/s21_floor.c.o

src/another/s21_floor.i: src/another/s21_floor.c.i
.PHONY : src/another/s21_floor.i

# target to preprocess a source file
src/another/s21_floor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/src/another/s21_floor.c.i
.PHONY : src/another/s21_floor.c.i

src/another/s21_floor.s: src/another/s21_floor.c.s
.PHONY : src/another/s21_floor.s

# target to generate assembly for a file
src/another/s21_floor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/src/another/s21_floor.c.s
.PHONY : src/another/s21_floor.c.s

src/comparison/s21_less.o: src/comparison/s21_less.c.o
.PHONY : src/comparison/s21_less.o

# target to build an object file
src/comparison/s21_less.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/src/comparison/s21_less.c.o
.PHONY : src/comparison/s21_less.c.o

src/comparison/s21_less.i: src/comparison/s21_less.c.i
.PHONY : src/comparison/s21_less.i

# target to preprocess a source file
src/comparison/s21_less.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/src/comparison/s21_less.c.i
.PHONY : src/comparison/s21_less.c.i

src/comparison/s21_less.s: src/comparison/s21_less.c.s
.PHONY : src/comparison/s21_less.s

# target to generate assembly for a file
src/comparison/s21_less.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/src/comparison/s21_less.c.s
.PHONY : src/comparison/s21_less.c.s

src/core/exponent.o: src/core/exponent.c.o
.PHONY : src/core/exponent.o

# target to build an object file
src/core/exponent.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/src/core/exponent.c.o
.PHONY : src/core/exponent.c.o

src/core/exponent.i: src/core/exponent.c.i
.PHONY : src/core/exponent.i

# target to preprocess a source file
src/core/exponent.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/src/core/exponent.c.i
.PHONY : src/core/exponent.c.i

src/core/exponent.s: src/core/exponent.c.s
.PHONY : src/core/exponent.s

# target to generate assembly for a file
src/core/exponent.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/src/core/exponent.c.s
.PHONY : src/core/exponent.c.s

src/core/sign.o: src/core/sign.c.o
.PHONY : src/core/sign.o

# target to build an object file
src/core/sign.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/src/core/sign.c.o
.PHONY : src/core/sign.c.o

src/core/sign.i: src/core/sign.c.i
.PHONY : src/core/sign.i

# target to preprocess a source file
src/core/sign.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/src/core/sign.c.i
.PHONY : src/core/sign.c.i

src/core/sign.s: src/core/sign.c.s
.PHONY : src/core/sign.s

# target to generate assembly for a file
src/core/sign.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/src/core/sign.c.s
.PHONY : src/core/sign.c.s

src/s21_decimal.o: src/s21_decimal.c.o
.PHONY : src/s21_decimal.o

# target to build an object file
src/s21_decimal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/src/s21_decimal.c.o
.PHONY : src/s21_decimal.c.o

src/s21_decimal.i: src/s21_decimal.c.i
.PHONY : src/s21_decimal.i

# target to preprocess a source file
src/s21_decimal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/src/s21_decimal.c.i
.PHONY : src/s21_decimal.c.i

src/s21_decimal.s: src/s21_decimal.c.s
.PHONY : src/s21_decimal.s

# target to generate assembly for a file
src/s21_decimal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/src/s21_decimal.c.s
.PHONY : src/s21_decimal.c.s

test.o: test.c.o
.PHONY : test.o

# target to build an object file
test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/test.c.o
.PHONY : test.c.o

test.i: test.c.i
.PHONY : test.i

# target to preprocess a source file
test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/test.c.i
.PHONY : test.c.i

test.s: test.c.s
.PHONY : test.s

# target to generate assembly for a file
test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s21_decimal.dir/build.make CMakeFiles/s21_decimal.dir/test.c.s
.PHONY : test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... s21_decimal"
	@echo "... src/another/s21_floor.o"
	@echo "... src/another/s21_floor.i"
	@echo "... src/another/s21_floor.s"
	@echo "... src/comparison/s21_less.o"
	@echo "... src/comparison/s21_less.i"
	@echo "... src/comparison/s21_less.s"
	@echo "... src/core/exponent.o"
	@echo "... src/core/exponent.i"
	@echo "... src/core/exponent.s"
	@echo "... src/core/sign.o"
	@echo "... src/core/sign.i"
	@echo "... src/core/sign.s"
	@echo "... src/s21_decimal.o"
	@echo "... src/s21_decimal.i"
	@echo "... src/s21_decimal.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

